# fly.toml app configuration file generated for logos-sophokleios on 2023-11-28T21:42:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "logos-sophokleios"
primary_region = "cdg"

[build]
  image = "ghcr.io/livebook-dev/livebook:0.11.3"

[env]
  ELIXIR_ERL_OPTIONS = "-proto_dist inet6_tcp"
  LIVEBOOK_DATA_PATH = "/files"
  LIVEBOOK_HOME = "/files"
  LIVEBOOK_IP = "::"
  LIVEBOOK_ROOT_PATH = "/files"
  PORT = "8080"

[[mounts]]
  source = "files"
  destination = "/files"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
